SELECT
ORDER_ID as ORDER_GUID
, USER_ID as USER_GUID
, PROMO_ID
, ADDRESS_ID as ADDRESS_GUID
, CREATED_AT
, ORDER_COST
, SHIPPING_COST
, ORDER_TOTAL
, TRACKING_ID as TRACKING_GUID
, SHIPPING_SERVICE
, ESTIMATED_DELIVERY_AT
, DELIVERED_AT
, STATUS

FROM {{ source('postgres_greenery', 'orders') }}